package com.hncr.ibms.tools

/**
 * Created by LG
 * on 2023/7/26  10:03
 * Description：
 */
const val EVENTBUS_TOAST_STRING = "EVENTBUS_TOAST_STRING"


const val EVENTBUS_FLOOR_DATA = "EVENTBUS_FLOOR_DATA"

const val EVENTBUS_FLOOR_ID = "EVENTBUS_FLOOR_ID"

const val EVENTBUS_FLOOR_USER = "EVENTBUS_FLOOR_USER"

const val EVENTBUS_SEARCH_USER = "EVENTBUS_SEARCH_USER"

const val EVENTBUS_ADDSUGGESTION_SUCCESS = "EVENTBUS_ADDSUGGESTION_SUCCESS"

